### ISSUE TITLE
Roadmap v1

### ISSUE THREAD

**Issue by chrisvdm** [chrisvdm/redwoodjs-stripe#1]
- [x] **Create Readme/Proposal for package**
- [x] **#3** (Dec 2021)
  - Gather Feedback
  - Fine tune
- [x] #4 (March 2021)
  - Purpose is to demonstrate the power of Stripe and Redwoodjs together
  - [Example store roadmap](https://github.com/redwoodjs/example-store/issues/9)
  -  Share with communities
- [x] **Use feedback and findings from POC to build package Version 1**
  - Features
    - Subscription payments via Stripe Checkout
      Includes:
      - Customer Portal creation
    - Once-off payments via Stripe Checkout
    - Simplified use of webhooks for Stripe events
    - Simplified cart
  - [x] Create example store using plugin (Jun 2022)
  - [x] Open to Stripe and Redwood communities to test before releasing V1 (Jun 2022)
    - Twitter
    - Community forums
    - [Github Discussions](https://github.com/chrisvdm/redwoodjs-stripe/discussions)
- [x] **Share with Redwood and Stripe community**

Version 1 ETA: **30 July 2022** 

_Disclaimer: Dates are generous estimates_

**Comment by chrisvdm** [comment]
Completed
