### ISSUE TITLE
Improve: setup script

### ISSUE THREAD

**Issue by chrisvdm** [chrisvdm/redwoodjs-stripe#37]
- [x] insert env vars instead of replacing `.env` file
- [x] insert schemas and services instead if replacing file (Or discuss better api for sharing schemas and services)
- [x] TS support (At very least not break)
- [ ] #126

_Note: This is a tracking for the current setup script as seen in **version 0.1.0-alpha.5**_
