### ISSUE TITLE
Features in detail: Setup

### ISSUE THREAD

**Issue by chrisvdm** [chrisvdm/redwoodjs-stripe#6]
### Setup
Features concerning the  installation/setting up of the integration
`yarn rw-stripe setup` 

`--one-time` or `--subscription` or no flags
- [x] #11
- [x] #12
- [x] create/edit '.env' 
- [x] map Users to Stripe Customers 🍬
- [x] hooks including api code
  - useCheckout
  - useProducts 🍬

`--subscription`
- [x] create db tbl for Users 🍬
- [x] hooks including api code
  - useCustomerPortal

_Disclaimer:
Names for functions and stuff subject to change. Also features will be added and removed as neccesary. 🍬 is used as a nice-to-have feature_

_Edit:
Removed setup for dbAuth_

**Comment by chrisvdm** [comment]
Feedback from the PoC to take into consideration
(Again thank you guys for looking into the PoC)
https://github.com/redwoodjs/payments/issues/7
https://github.com/redwoodjs/payments/issues/4
