### ISSUE TITLE
Roadmap v2

### ISSUE THREAD

**Issue by chrisvdm** [chrisvdm/redwoodjs-stripe#98]
- [ ] Typescript support
- [ ] Paystack integration
- [ ] Improve setup script
- [ ] Implement integration tests
- [ ] Stripe Elements
- [ ] Add more Stripe objects
- [ ] Dynamically create Stripe Schema
- [ ] Rename to Redwoodjs-payments

**Comment by ageddesi** [comment]
Hey @chrisvdm I will be using this package on my new saas project. If you need help one any of this work getting done I am happy to donate some time.
